lib{perfevent}: {hxx}{** -version} hxx{version}

hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

cxx.poptions =+ "-I$out_root" "-I$src_root"

lib{perfevent}: cxx.export.poptions = "-I$out_root" "-I$src_root"

{hxx}{*}:
{
  install         = include/perfevent/
  install.subdirs = true
}
